### ISSUE TITLE
Add syntax for Go-like slices

### ISSUE THREAD

**Issue by trichner** [fabianschuiki/low#1]
Syntax for slices is awesome.

```
struct slice{
 <type>* array,
 int  length,
 int capacity
}
```

example:

```
a = b[5:]
c = b[2:7]
d = b[:]
```

**Comment by fabianschuiki** [comment]
What's the point of the `capacity` field? How do you insert things into a slice?

**Comment by trichner** [comment]
capacity is the allocated underlying memory while length is the amount of filled up entries.

you access them like arrays `b[5] = 3`, it is then trivial to write a function that implements a `vector append` (either add element at `length` or double the capacity and then append it). In my opinion its a lightweight 'List'-ish datastructure.

Better explanation: https://blog.golang.org/go-slices-usage-and-internals

**Comment by trichner** [comment]
I'm not sure yet what should be done to correctly `free` (sub-)slices. Leave it to the programmer to `free` the correct pointer? Make deep copies?

Right now I'd vote for option 1.
