### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/low#9]
Add a `.travis.yml` file and enable this repository on Travis CI, such that we get immediate feedback on commits and pull requests, and have a central place to have the test cases run.

**Comment by trichner** [comment]
+1

**Comment by fabianschuiki** [comment]
Done. However, the apt repository on llvm.org seems to be down. This breaks the Travis CI build, since LLVM 3.6 is not available on Ubuntu 12.04 through the standard repositories, and needs to be installed via the llvm.org/apt repository.
